# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Outdoor Knife Guide
tagline:          'Find that perfect outdoor knife'
description:      'Help finding that perfect outdoor knife'
url:              http://outdoorknifeguide.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
